const SECOND_IN_MILLIS = 1000,
  MINUTE_IN_MILLIS = SECOND_IN_MILLIS * 60,
  HOUR_IN_MILLIS = MINUTE_IN_MILLIS * 60,
  DAY_IN_MILLIS = HOUR_IN_MILLIS * 24,
  WEEK_IN_MILLIS = DAY_IN_MILLIS * 7;

module.exports.SESSION_EXPIRY = DAY_IN_MILLIS * 7;
module.exports.SESSION_ROTATION_AFTER = MINUTE_IN_MILLIS * 20;

module.exports.DAY_IN_MILLIS = DAY_IN_MILLIS;
module.exports.MINUTE_IN_MILLIS = MINUTE_IN_MILLIS;
module.exports.SECOND_IN_MILLIS = SECOND_IN_MILLIS;
